# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: https://emanuelegdepaoli.github.io/santa-caterina-website/
# https://stackoverflow.com/questions/48197580/jekyll-theme-does-not-work-on-github-pages-but-works-locally
# baseurl: ''
title: 'Confraternita di S. Caterina, Biandrate'
description:
permalink: pretty
# for logo, don't put ./but just /
logo: '/pictures/logo.jpg'
encoding: utf-8 # Make sure the encoding is right
lang: it # Set the site language
description: "Alembic is a starting point for Jekyll projects. Rather than starting from scratch, this boilerplate is designed to get the ball rolling immediately" # Site description and default description, also used in jekyll-seo-tag
thanks_url: https://formspree.io/f/xoqzaozw # url formspree
# google_analytics: ""
# google_analytics_anonymize_ip: ""
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Chi siamo
  url: /storia
- title: La nostra chiesa
  url: /chiesa
- title: Galleria
  url: /galleria
- title: Contatti
  url: /contatti
- title: Blog
  url: /blog/



# Footer nav
navigation_footer:
- title: Torna in cima
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""
    feature_text: |
      Blog di Santa Caterina
    feature_image: ""

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
